[pre-commit]
parallel = true

[pre-commit.commands.black]
glob = "*.py"
run = "python -m black {staged_files}"
stage_fixed = true

[pre-commit.commands.isort]
glob = "*.py"
run = "python -m isort {staged_files}"
stage_fixed = true

[pre-commit.commands.flake8]
glob = "*.py"
run = "python -m flake8 {staged_files}"

[commit-msg]
parallel = false

[commit-msg.commands.commitlint]
run = "npx --no -- commitlint --edit {1}"
